trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 200
  benchmark: True

program:
  data_dir: '/torchgeo_data/cvpr_chesapeake_landcover'
  overwrite: True

experiment:
  task: "chesapeake_learn_on_prior"
  name: "chesapeake_train_on_prior"
  module:
    loss: "qr_forward"  
    segmentation_model: "fcn"
    activation_layer: "logsoftmax" 
    optimizer: "adamw"
    learning_rate: 1e-3
    output_smooth: 1e-4
    learning_rate_schedule_patience: 4
    num_filters: 256
  datamodule:
    batch_size: 64
    patch_size: 128
    patches_per_tile: 400
    num_workers: 4
    train_state: "de"
    train_set: "val"
    use_prior_labels: True
    class_set: 5
    prior_smoothing_constant: 1e-4