trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 200
  benchmark: True

program:
   data_dir: '/datadrive/esther/torchgeo_data'
   overwrite: True
    
experiment:
  task: "enviroatlas_learn_the_prior"
  name: "enviroatlas_learn_the_prior"
  module:
    loss: "nll"  # cross entropy loss
    segmentation_model: "fcn_larger"
    optimizer: "adamw"
    output_smooth: 1e-4
    learning_rate_schedule_patience: 4
  datamodule:
    batch_size: 128
    patch_size: 128
    patches_per_tile: 800
    num_workers: 8
