trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True

program:
   data_dir: '/home/esther/torchgeo_data/enviroatlas'
   overwrite: True
    
experiment:
  task: "enviroatlas"
  name: "enviroatlas_train_on_highres"
  module:
    loss: "qr_forward"  # cross entropy loss
    segmentation_model: "fcn"
    activation_layer: "logsoftmax" 
    optimizer: "adamw"
    learning_rate: 1e-3
    output_smooth: 1e-4
    learning_rate_schedule_patience: 4
  datamodule:
    batch_size: 64
    patch_size: 128
    patches_per_tile: 800
    num_workers: 4
  #  train_state: "de"
   # condense_barren: True
  #  train_set: "val"