trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 200
  benchmark: True

program:
   data_dir: '/datadrive/esther/torchgeo_data'
   overwrite: True
    
experiment:
  task: "enviroatlas_learn_on_prior"
  name: "enviroatlas_train_on_prior"
  module:
    loss: "qr_forward"  # cross entropy loss
    segmentation_model: "fcn"
    optimizer: "adamw"
    learning_rate: 1e-3
    output_smooth: 1e-4
    learning_rate_schedule_patience: 4
    num_filters: 128
  datamodule:
    batch_size: 128
    patch_size: 128
    patches_per_tile: 800
    num_workers: 8
