experiment:
  task: "chesapeake_learn_on_prior"
  module:
    loss: "qr_forward"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 4
    condense_barren: True
    output_smooth: 1e-4
  datamodule:
    batch_size: 64
    patch_size: 128
    patches_per_tile: 400
    num_workers: 4
    train_state: "de"
    condense_barren: True
    train_set: "val"